apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejsweb
  name: nodejsweb
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: nodejsweb
